PyErr_Format(PyExc_TypeError, "Dataset %s not found", value_list.type);